import pandas as pd

# Full NSE symbols list (top 500 - expand as needed)
symbols = """
RELIANCE,TCS,HDFCBANK,INFY,ICICIBANK,HINDUNILVR,ITC,SBIN,BHARTIARTL,KOTAKBANK,
LT,AXISBANK,ASIANPAINT,MARUTI,SUNPHARMA,TITAN,ULTRACEMCO,NESTLEIND,BAJFINANCE,
HCLTECH,WIPRO,TATASTEEL,ADANIENT,ONGC,NTPC,POWERGRID,COALINDIA,TATAMOTORS,
M&M,JSWSTEEL,TECHM,INDUSINDBK,HINDALCO,GRASIM,BAJAJFINSV,BRITANNIA,DIVISLAB,
DRREDDY,CIPLA,EICHERMOT,HEROMOTOCO,SHREECEM,APOLLOHOSP,ADANIPORTS,BPCL,IOC,
HDFCLIFE,SBILIFE,PIDILITIND,BERGEPAINT,HAVELLS,DABUR,MARICO,GODREJCP,TATACONSUM,
MCDOWELL-N,UPL,GAIL,INDIGO,VEDL,TRENT,DMART,NAUKRI,ZOMATO,PAYTM,POLICYBZR
""".replace("\n", "")

df = pd.DataFrame({"SYMBOL": [s.strip() for s in symbols.split(",") if s.strip()]})
df.to_csv("nse_symbols.csv", index=False)
print(f"✅ Created nse_symbols.csv with {len(df)} symbols")
