import os, time
from pathlib import Path

def get_recent_files(directory, max_files=10, hours_ago=72):
    cutoff_time = time.time() - (hours_ago * 3600)
    recent_files = []
    ignore_dirs = {'.git', '.agents', '.kilo', '.vscode', 'venv', '__pycache__', 'node_modules', 'data'}
    allowed_exts = {'.py', '.json', '.md', '.csv', '.bat', '.ts', '.js'}
    
    try:
        for root, dirs, files in os.walk(directory):
            dirs[:] = [d for d in dirs if d not in ignore_dirs]
            for file in files:
                filepath = Path(root) / file
                if filepath.suffix in allowed_exts:
                    try:
                        mtime = filepath.stat().st_mtime
                        if mtime > cutoff_time:
                            recent_files.append((filepath, mtime))
                    except Exception:
                        pass
    except Exception as e:
        print(f"Error scanning {directory}: {e}")

    recent_files.sort(key=lambda x: x[1], reverse=True)
    return [f[0] for f in recent_files[:max_files]]

def generate_context_file():
    base_dir = Path(__file__).resolve().parent.parent.parent

    content = [
        "# ACTIVE SESSION CONTEXT\n",
        "> **AUTOMATED:** Generated by `generate_context.py`. Do not edit manually.\n",
        f"\n**Current Working Set ({base_dir.name}):**"
    ]

    recent = get_recent_files(base_dir)
    for f in recent:
        content.append(f"- `{base_dir.name}/{f.relative_to(base_dir)}`")
    if not recent:
        content.append("- *(No recently modified files found)*")

    content.extend([
        "\n**Constraints for Today:**",
        "- Do NOT hallucinate variables or schemas. Use Dynamic Schema Discovery.",
        "- Production directories (Streamlit files) are READ-ONLY. Propose changes as code blocks only."
    ])

    context_dir = base_dir / '.agents' / 'rules'
    context_dir.mkdir(parents=True, exist_ok=True)
    
    context_path = context_dir / 'CONTEXT.md'
    context_path.write_text('\n'.join(content), encoding='utf-8')
    print(f"Context generated -> {context_path}")

if __name__ == '__main__':
    generate_context_file()
